### 1. Create a null vector of size 10 but the fifth value which is 1.


In [1]:
import numpy as np

n = 7   

null_vector = np.zeros(10)

null_vector[n-1] = 1

print(null_vector)


[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49.


In [2]:
import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3. Create a 3x3 matrix with values ranging from 0 to 8


In [6]:
import numpy as np

matrix = np.arange(9).reshape((3, 3))

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [7]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [8]:
import numpy as np
array = np.random.rand(10, 10)
minimum = np.min(array)
maximum = np.max(array)

print("Array:")
print(array)
print("Minimum value:", minimum)
print("Maximum value:", maximum)


Array:
[[0.4079282  0.55750999 0.21904018 0.78278547 0.30002062 0.92724313
  0.35909283 0.87557774 0.98155339 0.88986081]
 [0.59117014 0.10581385 0.19745552 0.96071376 0.80083284 0.31227162
  0.72853927 0.68593188 0.23919983 0.31604841]
 [0.42523923 0.36736005 0.35817357 0.43629723 0.64469956 0.21630641
  0.66391517 0.84167456 0.97999482 0.77579363]
 [0.31657198 0.32967015 0.23214267 0.10914016 0.14288536 0.95454821
  0.02347718 0.64270954 0.28781769 0.28887473]
 [0.5161633  0.7513056  0.56139333 0.10023649 0.66347966 0.05336387
  0.99441613 0.07251423 0.6196465  0.81274902]
 [0.43976003 0.77727416 0.78857543 0.33103621 0.68739283 0.44016383
  0.33099948 0.9661166  0.94664988 0.95131758]
 [0.24692383 0.26298905 0.05049081 0.51978201 0.99489337 0.11275457
  0.61586599 0.83314038 0.45770366 0.21084344]
 [0.11595018 0.58052893 0.79924939 0.94703066 0.95283444 0.53577364
  0.67538169 0.60667809 0.17987462 0.61392756]
 [0.30140986 0.82900688 0.37113494 0.91305485 0.06654274 0.81615193
  0.0

### 6. Create a random vector of size 30 and find the mean value.


In [9]:
import numpy as np

vector = np.random.rand(30)
mean = np.mean(vector)

print("Vector:")
print(vector)
print("Mean value:", mean)


Vector:
[0.46510077 0.22912394 0.27777579 0.34823941 0.14337628 0.78463677
 0.12745864 0.26381999 0.988035   0.58312322 0.48795927 0.40432371
 0.35687479 0.91478066 0.50055936 0.32361074 0.423637   0.86066441
 0.56864243 0.02192887 0.95105809 0.65841667 0.9702822  0.08153245
 0.8424637  0.95727859 0.36741305 0.81259976 0.81939764 0.52006465]
Mean value: 0.5351392619986828
